### ISSUE TITLE
nextTick 执行回调的原因是什么？

### ISSUE THREAD

**Issue by xiaoshude** [node-modules/ready#6]
https://github.com/node-modules/ready/blob/89c9a0fca48cfc6e0ec000e1fa4710301bef4ca2/index.js#L73

**Comment by alsotang** [comment]
要等待ready的事件不一定是异步的，可能是同步。当同步时，过早触发了ready的回调，导致后面的一些监听被忽略了。这里应该是为了避免这类事情发生所以加了个 nextTick。

**Comment by xiaoshude** [comment]
总结下：
1. 保证在 emit ready 事件发出之后，同步 register 的回调也会被执行
2. 符合 js 事件的直觉，在同步代码之后，下次事件循环执行
